import {GameEngine} from './gameEngine.js';
import {best,reset,read} from './storage.js';
import {sameRatioGame} from './games/sameRatio.js';
import {simplifyRatioGame} from './games/simplifyRatio.js';
import {ratioValueGame} from './games/ratioValue.js';
import {memoryRatioGame} from './games/memoryRatio.js';
const app=document.querySelector('#app');
const games=[sameRatioGame,simplifyRatioGame,ratioValueGame,memoryRatioGame];
const labels={easy:'EASY',normal:'NORMAL',hard:'HARD'};let activeEngine=null;
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function header(){return `<header class="brand"><div class="brand-mark">⚖</div><div><h1>RATIO PARK</h1><p>いろいろなゲームで、比の感覚をみがこう！</p></div></header>`}
function home(){activeEngine?.stop();activeEngine=null;const level=location.hash.match(/level=(easy|normal|hard)/)?.[1]||'easy';app.innerHTML=`${header()}<section class="hero"><h2>比のアトラクションへ、ようこそ。</h2><p>見て、考えて、タップ！ 60秒で何問できるかな？<br>正確に続けるほど、コンボで得点アップ。</p><div class="difficulty">${Object.entries(labels).map(([k,v])=>`<button class="${k===level?'active':''}" data-level="${k}">${v}</button>`).join('')}</div></section><div class="section-title"><h2>🎡 アトラクションをえらぼう</h2><span class="mode">${labels[level]}</span></div><section class="game-grid">${games.map((g,i)=>`<button class="game-card" data-game="${g.id}"><div class="card-top"><div class="game-icon">${['◎','÷','½','🂠'][i]}</div><div><small>GAME 0${i+1}</small><h3>${g.title}</h3></div></div><p>${[g.hint||'同じ比を見つけよう！','同じ数で割って、いちばん簡単な比へ。','比の値を、分数でキャッチ！','等しい比のペアを集めよう！'][i]}</p><div class="best-line">BEST SCORE <strong>${best(g.id,level).toLocaleString()}</strong></div></button>`).join('')}</section><div class="section-title"><h2>🚧 次のアトラクション</h2></div><div class="soon-grid">${['ニセモノを探せ！','穴あき比','どっちが大きい？','比チェーン'].map((x,i)=>`<div class="soon">GAME 0${i+5}<br><b>${x}</b><br>COMING SOON</div>`).join('')}</div><button class="reset-link" data-reset>記録をリセット</button>`;app.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{location.hash=`#home?level=${b.dataset.level}`;home()});app.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game,level));app.querySelector('[data-reset]').onclick=()=>{if(confirm('すべての記録を消しますか？')){reset();home()}}}
function gameHead(g,level,e){return `<button class="back" data-home>← パークにもどる</button><div class="game-head"><div><span class="mode">${labels[level]}</span><h2>${g.title}</h2></div><div class="stats"><div class="stat">TIME<strong>${e.time}</strong></div><div class="stat">SCORE<strong>${e.score}</strong></div><div class="stat">COMBO<strong>${e.combo}</strong></div></div></div>`}
function start(id,level){const g=games.find(x=>x.id===id);let q=g.newQuestion(level),feedback='';const engine=new GameEngine({game:id,level,onRender:event=>{if(event.phase==='countdown'){app.innerHTML=`${header()}<section class="screen-card countdown">${event.word}<span>まもなくスタート！</span></section>`;return}if(event.phase==='answer'){feedback=event.near?'△ あと一歩！':event.ok?'○ GOOD!':'× もう一度考えよう';setTimeout(()=>feedback='',900)}render()},onEnd:state=>result(g,level,state)});activeEngine=engine;
  function render(){if(!engine.active&&engine.time>0)return;app.innerHTML=`${header()}<section class="screen-card">${gameHead(g,level,engine)}<div class="feedback ${feedback.startsWith('○')?'good':feedback.startsWith('×')?'bad':feedback?'near':''}">${feedback}</div>${g.render(q)}</section>`;app.querySelector('[data-home]').onclick=()=>{engine.stop();location.hash='#home';home()};bind()}
  function next(){q=g.newQuestion(level);engine.unlock();render()}
  function bind(){if(id==='sameRatio')app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const choice=q.choices[Number(b.dataset.choice)];if(!engine.answer(choice.ok,{weakness:'sameRatio'}))return;b.classList.add(choice.ok?'correct':'wrong');if(choice.ok){engine.correct++;setTimeout(next,260)}else setTimeout(()=>{engine.unlock();render()},450)});
    if(id==='simplifyRatio'){const finish=app.querySelector('[data-finish]');if(finish)finish.onclick=()=>{if(!engine.answer(true,{bonus:g.bonus(q)}))return;engine.correct++;setTimeout(next,250)};app.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{const ok=g.apply(q,q.options[Number(b.dataset.op)]);if(!engine.answer(ok,{weakness:'simplifyRatio'}))return;if(ok){engine.unlock();render()}else setTimeout(()=>{engine.unlock();render()},450)});
    if(id==='ratioValue'){app.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>{q.active=b.dataset.field});app.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>{const k=b.dataset.key;if(k==='C'){q[q.active]='';render();return}if(k==='✓'){const r=g.judge(q);if(r.type==='near'){feedback=r.message;engine.answer(true,{near:true});engine.unlock();render();return}if(r.type==='correct'){if(engine.answer(true)){engine.correct++;feedback=r.message;setTimeout(next,320)}return}engine.miss('ratioValue');feedback=r.message;setTimeout(()=>{engine.unlock();render()},550);return}q[q.active]=String(q[q.active]||'')+k;render()})}
    if(id==='memoryRatio')app.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{if(!engine.active||engine.locked)return;const r=g.flip(q,Number(b.dataset.card));if(!r)return;render();if(r.type==='match'){if(engine.answer(true)){engine.correct++;feedback='○ MATCH!';setTimeout(()=>{if(q.cards.every(c=>c.state==='matched'))q=g.newQuestion(level);engine.unlock();render()},260)}}if(r.type==='miss'){engine.miss('memoryRatio');feedback='× ちがうペア';setTimeout(()=>{r.cards.forEach(c=>c.state='down');q.open=[];engine.unlock();render()},600)}})}
  engine.start();}
function result(g,level,s){const total=s.correct+s.wrong,rate=total?Math.round(s.correct/total*100):0;app.innerHTML=`${header()}<section class="screen-card result"><span class="mode">${labels[level]} / ${g.title}</span><p>SCORE</p><div class="score">${s.score.toLocaleString()}</div>${s.saved.isNew?'<div class="new-best">★ NEW BEST!</div>':''}<div class="result-grid"><div>BEST<strong>${s.saved.best.toLocaleString()}</strong></div><div>正解<strong>${s.correct}</strong></div><div>ミス<strong>${s.wrong}</strong></div><div>最高コンボ<strong>${s.maxCombo}</strong></div><div>正答率<strong>${rate}%</strong></div></div><div class="result-actions"><button class="primary" data-again>もう一回！</button><button class="secondary" data-levels>難易度を変える</button><button class="secondary" data-home>ホームへ</button></div></section>`;app.querySelector('[data-again]').onclick=()=>start(g.id,level);app.querySelector('[data-levels]').onclick=()=>{location.hash=`#home?level=${level}`;home()};app.querySelector('[data-home]').onclick=()=>{location.hash='#home';home()}}
window.addEventListener('hashchange',home);home();
